(define (smallest n)
  (find-divisor n 2))
(define (find-divisor n start)
  (cond ((> (square start) n) n)
        ((divides? n start) start)
        (else (find-divisor n (+ start 1)))))
(define (square s)
  (* s s))
(define (divides? n s)
  (= (remainder n s) 0))
(smallest 199)
(smallest 1999)
(smallest 19999)
      